name: FlyHigh CI with Allure

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  USERNAME: ${{ secrets.USER }}
  PASSWORD: ${{ secrets.PASSWORD }}

permissions:
  contents: read
  # dependency-submission: write  # Раскомментируйте если нужен Dependency Graph

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Run tests with Maven
        run: mvn clean test -Duser=$USERNAME -Dpassword=$PASSWORD

      - name: Generate Allure Report
        if: always()  # Генерировать отчет даже если тесты упали
        run: |
          mvn allure:report
          echo "ALLURE_RESULTS_DIR=target/allure-results" >> $GITHUB_ENV

      - name: Upload Allure Report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: allure-report
          path: target/site/allure-maven-plugin


      - name: Publish Allure Report
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: target/site/allure-maven-plugin
          destination_dir: allure-report

    # Опционально: Dependency Graph (раскомментируйте если нужно)
    # - name: Update dependency graph
    #   uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6