name: FlyHigh CI with Allure

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  USERNAME: ${{ secrets.USER }}
  PASSWORD: ${{ secrets.PASSWORD }}

permissions:
  contents: read
  actions: write  # Необходимо для загрузки артефактов

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Run tests with Maven
        run: mvn clean test -Duser=$USERNAME -Dpassword=$PASSWORD

      - name: Generate Allure Report
        if: always()
        run: mvn allure:report

      - name: Upload Allure Report
        if: always()
        uses: actions/upload-artifact@v4  # Используем последнюю версию v4
        with:
          name: allure-report
          path: target/site/allure-maven-plugin