name: Allure Report

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  USERNAME: ${{ secrets.USER }}
  PASSWORD: ${{ secrets.PASSWORD }}

permissions:
  contents: write

jobs:
  test-and-report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Run tests with Allure listener
        run: |
          mvn clean test -Duser=$USERNAME -Dpassword=$PASSWORD \
          -Dallure.results.directory=target/allure-results

      - name: Verify test results
        run: |
          echo "Allure results files:"
          ls -la target/allure-results/
          echo "Surefire reports:"
          ls -la target/s