name: FlyHigh

on:
  push:
    branches: ["master"]  # Триггер на пуши в master
  pull_request:
    branches: ["master"]

env:
  USERNAME: ${{ secrets.USER }}
  PASSWORD: ${{ secrets.PASSWORD }}

permissions:
  contents: write  # Необходимо для публикации на GitHub Pages

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Run tests
        run: mvn clean test -Duser=$USERNAME -Dpassword=$PASSWORD

      - name: Generate Allure Report
        if: always()  # Генерировать даже если тесты упали
        run: mvn allure:report

      - name: Deploy Allure Report
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: target/site/allure-maven-plugin  # исходная папка с отчётом
          destination_dir: /  # загружаем в корень gh-pages